### ISSUE TITLE
Error with duplicate package found in 2 separate `node_modules`

### ISSUE THREAD

**Issue by yachaka** [darrenscerri/duplicate-package-checker-webpack-plugin#12]
Hi,

First, thanks for the package.
I'm having an error with a duplicate package, which is what I wanted, but the problem is that the duplicates are found inside `node_modules`, so I do not have the possibility to modify it.

It would be great to have an option to throw an error only when one of the duplicate is found in one of my own files.

**Comment by darrenscerri** [comment]
Hi @yachaka . Once https://github.com/darrenscerri/duplicate-package-checker-webpack-plugin/pull/13 is merged this would be possible by excluding duplicates by `issuer`
