### ISSUE TITLE
Add output to stats?

### ISSUE THREAD

**Issue by raulferras** [darrenscerri/duplicate-package-checker-webpack-plugin#3]
I ignore if this is possible, but could be useful to add a report to stats generated by webpack instead of outputting the result of the inspection.

I'm using webpack from another application and I expect the output to be a JSON (using --json option).
If not possible, consider outputting your result to a specified file instead like this other plugin is doing [BundleAnalyzer](https://www.npmjs.com/package/webpack-bundle-analyzer)

**Comment by darrenscerri** [comment]
In 1.1.0, `console.log` and `console.warn` is no longer used and warnings are passed as compilation warnings and can be found in the `stats.json`, so this issue can be closed.
