### ISSUE TITLE
Issue with output in stats

### ISSUE THREAD

**Issue by skipjack** [darrenscerri/duplicate-package-checker-webpack-plugin#4]
First off, thanks for this plugin! I'm running into a small issue when generating and uploading json stats to the various analyzer tools which is caused by this line in the output `stats.json` file:

![image](https://cloud.githubusercontent.com/assets/8988697/23273960/099c7c4a-f9cf-11e6-897c-cfb38067f4ef.png)

Not sure if you can control it outputting there or maybe if there's something I need to add to my config. Either way, any advice would be much appreciated as I'd like to keep using this plugin but also figure out how to make it play nice with the stats output. Maybe the warnings/errors can be included somewhere in the actual JSON.

**Comment by darrenscerri** [comment]
How are you generating the `stats.json`?

**Comment by darrenscerri** [comment]
In 1.1.0, `console.log` and `console.warn` is no longer used, so this issue can be closed.

**Comment by skipjack** [comment]
Generating them using the CLI:

```bash
webpack --profile --json > stats.json
```

Thanks for the quick fix!
