### ISSUE TITLE
Source of the duplicate package

### ISSUE THREAD

**Issue by jens-duttke** [darrenscerri/duplicate-package-checker-webpack-plugin#5]
Would it be possible to show more information about the source of the problem?

Especially
- Which packages refer to the different versions? (including the whole path from my package.json to the problematic packages).
- Which modules (files) of the package have a reference to the problematic package?
- Which parts of the problematic package are included? (only specific functions? files? the whole package?)
- What's the size of each version of the problematic package?

I think these information would be useful to decide how to solve the problems.

**Comment by darrenscerri** [comment]
The path is being displayed since v1.2.0. I think that's quite enough information to provide you with a good starting point. If you think that the other points should also be tackled, I suggest you open separate issues for each point to initiate more specific discussions.
